name: flutter_beautify
description: A beautiful custom widget cli for Flutter.
version: 1.0.4

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0


homepage: https://github.com/DeveloperRejaul/flutter_beautify
repository: https://github.com/DeveloperRejaul/flutter_beautify


executables:
  flutter_beautify: